[package]
name = "rust-aoc"
version = "0.1.0"
authors = ["Cameron McCallie <mccallie.cameron@gmail.com>"]

[dependencies]
aoc_runner = { version = "*", package = "aoc-runner" }
aoc_runner_derive = { version = "*", package = "aoc-runner-derive" }
